### PR TITLE
SeqTarget - Added MaxRecursionLimit property to allow property reflection

### LINKED ISSUE #32: Enhancement: add support for includeAllProperties option
When serializing to a file it is possible to serialize all properties with layout render like this:

`   <layout xsi:type="JsonLayout" includeAllProperties="true" maxRecursionLimit="20" excludeProperties="...." >`

It is not possible to add includeAllProperties, maxRecursionLimit and excludeProperties to seq target.

**Background for this request**:
I am trying to log properties using nlog-targests-seq so they are searchable.
I know I can use @ to serialize objects in messages - but is seems not possible for user properties?

Pseudo c# code that works (I can e.g. search for x.status=0 i seq):
`class MyClass { public int status { get; set; } };`
`var x = new MyClass();`
`log.Debug().Message("Write {@x}", x).Write();`

Pseudo c# code not working (only x class name is serialized so I can not search for x.status=0):
`class MyClass { public int status { get; set; }`
`var x= new MyClass();`
`log.Debug().Message("Write Hi").Property("x", x).Write();`

Today I have to format every property into the message string - this does not seem like an optimal method for structured logging.

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to resolve #32 (And some optimizations)

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks Rolf! Much appreciated. Will take a look first thing Monday :+1:

**Comment by snakefoot** [comment]
@nblumhardt Can see the old NLog-SeqClient grouped all properties below a separate "Properties"-key. Now all properties (custom + async-context) are placed just below the "root". I guess this is intended and supported by Seq?

**Comment by nblumhardt** [comment]
@snakefoot yes, Seq accepts two different JSON formats - the old one used a `Properties` key, the newer one flattens everything out at the root :+1:

**Comment by nblumhardt** [comment]
Just made one very minor formatting tweak - otherwise LGTM, merged to `dev`.

**Pull request merged**
