### PR TITLE
fix: force closing the stream returned by request.GetRequestStream()

### PR DESCRIPTION
**Pull request by LonghronShen**
The driver has a wired problem for .NET Core 3.0.
I observed that there were too many CLOSE_WAIT connections when the library used in Linux Docker.
The **strace** indicates that the driver seems not disposing the socket connection.
Since the **StreamWriter** class has an overload says:
```C#
StreamWriter(... bool leaveOpen = false)
```
It should work, but not.
Fallback to the following workaround works.

In **PostBatch()** function, change
```C#
using (var payload = new StreamWriter(request.GetRequestStream()))
```
into 
```C#
using (var responseStream = request.GetRequestStream())
{
    using (var payload = new StreamWriter(responseStream))
```

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the report! I dug into this some more, it seems this is a limitation of `HttpWebRequest` on .NET Core; there was [a partial mitigation](https://github.com/dotnet/corefx/issues/15460) but no complete fix, and the .NET developers [are recommending](https://github.com/dotnet/corefx/issues/26373#issuecomment-358164114) a move to `HttpClient`.

I'll take a look at switching this library to `HttpClient`, rather than tinker with the current implementation, for now.

**Comment by LonghronShen** [comment]
Thank you for your notification to the problem!Yeah, the HttpClient is recommended for a long time since 2009. Switching to use that is a better way.

Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: Nicholas Blumhardt <notifications@github.com>
发送时间: Wednesday, December 11, 2019 7:15:00 AM
收件人: datalust/nlog-targets-seq <nlog-targets-seq@noreply.github.com>
抄送: Steven Hangger <LonghronShen@Hotmail.com>; Author <author@noreply.github.com>
主题: Re: [datalust/nlog-targets-seq] fix: force closing the stream returned by request.GetRequestStream() (#47)


Thanks for the report! I dug into this some more, it seems this is a limitation of HttpWebRequest on .NET Core; there was a partial mitigation<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx%2Fissues%2F15460&data=02%7C01%7C%7C337273f85890493fea5d08d77dc6c899%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637116165027026656&sdata=hSx9XW3NWrUfwa6bxLbIQZ9GddTy7Y5NRRWVMDPiEZE%3D&reserved=0> but no complete fix, and the .NET developers are recommending<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx%2Fissues%2F26373%23issuecomment-358164114&data=02%7C01%7C%7C337273f85890493fea5d08d77dc6c899%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637116165027036664&sdata=H4ddr%2FivvBR2oh19ULFyddHowIZxdG%2FW5xy2AClldK4%3D&reserved=0> a move to HttpClient.

I'll take a look at switching this library to HttpClient, rather than tinker with the current implementation, for now.

―

**Comment by snakefoot** [comment]
@nblumhardt Since rewrite to HttpClient is probably far down the todo-list, then I think this PR should be merged, and a ver. NLog.Targets.Seq 1.2.0 should be released.

**Comment by nblumhardt** [comment]
Thanks for the note. I didn't merge this because it's unclear the PR modifies the behavior - although the PR separates stream disposal from writer disposal, the underlying issue is not with disposal but rather with how connections are managed by the framework.

**Comment by snakefoot** [comment]
Yes you are right. See that StreamWriter automatically performs dispose of provided stream. Actually have to do extra magic to avoid this (Constructor with `bool leaveOpen`-parameter)

**Comment by nblumhardt** [comment]
Thanks for taking a look @snakefoot - I've opened #48 to get the other 1.2.0 changes out, and will loop back around to this later and see whether I can move it to `HttpClient` without too much drama.

**Comment by nblumhardt** [comment]
Addressing this in #52 - thanks for the original PR here, @LonghronShen .

**Pull request closed without merging**
