### PR TITLE
Support override of mapping from NLog LogLevel to Seq Level

### PR DESCRIPTION
**Pull request by snakefoot**
See also: https://github.com/datalust/seq-tickets/discussions/2117
```xml
<target xsi:type="Seq" serverUrl="http://localhost:5341" apiKey="" seqLevel="${event-properties:SubLevel:whenEmpty=${level}}" />
```

### CODE REVIEW

**Comment by snakefoot** [comment]
Since Seq supports any Level-value, then one might change NLog to output Microsoft Extension ILogger Loglevel (Thus `Warning` + `Information`). So it is not just for adding `SubLevel`.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; seems aligned with the NLog way of approaching it - works for me :+1:

**Comment by NameOfTheDragon** [comment]
I'm missing something on how this is supposed to work. I thought I understood it but now I come to use it I can't find the explanation that I thought I understood ;-) How do I tell NLog to write a log level other than it's built-in "cast-in-stone" levels?

**Comment by nblumhardt** [comment]
@NameOfTheDragon I think it should be something like:

```csharp
logger.WithProperty("SubLevel", "Audit").Info("Hello, world!");
```

HTH,
Nick

**Pull request merged**
