### PR TITLE
Update to NLog 4.5-beta06

### PR DESCRIPTION
**Pull request by nblumhardt**
Muuuuch better, thanks @snakefoot & @304NotModified 👍

### CODE REVIEW

**Comment by snakefoot** [comment]
@nblumhardt Maybe only insert into the captureTypes-dictionary, when the capturetype is different from normal? (Then you might save the alloction of the entire dictionary with extra lookups)

**Comment by snakefoot** [comment]
@nblumhardt I know this is an white-box implementation detail, but requesting MessageTemplateParameters actually has an overhead in NLog, so maybe you want to save it in a local variable and reuse that instead.

**Comment by snakefoot** [comment]
@nblumhardt Instead of doing this iteration:

```
for (var i = 0; i < logEvent.Parameters.Length; ++i)
{
   var name = i.ToString(CultureInfo.InvariantCulture);
```

Then you could do this, and save some string-alllocations:

```
for (var i = 0; i < messageTemplateParameters.Count; ++i)
{
    var name = messageTemplateParameters[i].Name;
```

**Comment by snakefoot** [comment]
@nblumhardt If you want to optimize the Layout-rendering, then you should change this:

`var stringValue = property.Value.Render(logEvent);`

Into this:

`var stringValue = RenderLogEvent(property.Value, logEvent);`

And enable the following setting your target-constructor:

`OptimizeBufferReuse = true;`

**Comment by snakefoot** [comment]
Instead of having your own Json-encoding in the target, then you could try the NLog-JsonEncoder:

`ConfigurationItemFactory.Default.JsonConverter`

**Comment by snakefoot** [comment]
@nblumhardt When overriding this method:

`protected override void Write(IList<AsyncLogEventInfo> asyncLogEvent)`

Then you should call this method on write complete for each item (where ex = null when success):

`asyncLogEvent.Continuation(Exception ex);`

This allow NLog-flush to work correctly.

**Comment by 304NotModified** [comment]
> @nblumhardt I know this is an white-box implementation detail, but requesting MessageTemplateParameters

Maybe we reconsider to make this more explicit? (e.g. no property but method)

**Comment by snakefoot** [comment]
Have no opinion about this, but it could make it more clear, that it doesn't return the same object every time



Sent from my Samsung device


-------- Original message --------

**Comment by nblumhardt** [comment]
> @nblumhardt Instead of doing this iteration:
> ...
> Then you could do this, and save some string-alllocations:
> ...

Will this always work, even when the message template contains out-of-order or repeated parameters? (`"{1} {0} {0}"`, etc.)

Thanks for all of the feedback; I've made a few changes, will PR them shortly, and raise issues to investigate the JSON formatting.

**Comment by snakefoot** [comment]
> Will this always work, even when the message template contains out-of-order or repeated parameters? 

Yes for IsPositional = true then MessageTemplateParameters will include repeated parameters (in case they should have different formatting).

When IsPositional = false, then it is expected that message-parameters has unique names, or they will be made so.

**Comment by snakefoot** [comment]
@nblumhardt You forgot logEvent.MessageTemplateParameters.IsPositional :)


Sent from my Samsung device


-------- Original message --------

**Comment by nblumhardt** [comment]
Thanks @snakefoot, I'll loop back around to this later in the week, and let you know how I go 👍

**Pull request merged**
