### PR TITLE
Add DefaultCredentials option 

### PR DESCRIPTION
**Pull request by alexander-kucherov**
We work in complex Windows enterprise infrastructure.
Our stage and prod Seq servers are behind TMG with Kerberos auth and we need UseDefaultCredentials option.
We've forked this repository many times for this reason.
My team and I would be really grateful if you could take these changes.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the PR! Happy to help make this happen 👍 

Since the default `HttpClientHandler` varies by framework version (and by platform in some cases IIRC), I don't think we should eagerly construct an `HttpClientHandler` when `UseDefaultCredentials` is `false`.

Could we only create an `HttpClientHandler` if either `UseDefaultCredentials` or `ProxyAddress` is specified? This would make it a very low risk change that we can more easily merge/release.

**Comment by alexander-kucherov** [comment]
Ok.
I don't eagerly construct an HttpClientHandler when UseDefaultCredentials is false.
I've just made changes.

**Comment by nblumhardt** [comment]
Looks good to me; I'll merge this so that a `-dev-*` package is published to NuGet, it would be great to hear how it goes, we should be able to publish from `main` once it's had some validation in the wild.

**Comment by alexander-kucherov** [comment]
We deployed our service with this dev package and everything works correctly.

**Comment by nblumhardt** [comment]
Excellent - thank you, Alexander.

**Pull request merged**
